service: aws-lambda-memcached
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  memcached:
    handler: index.handler
    vpc:
      subnetIds:
        - Ref: PrivateSubnetA
        - Ref: PrivateSubnetB
      securityGroupIds:
        - Fn::GetAtt: [ VPC, DefaultSecurityGroup ]
    environment:
      memcachedUrl: !GetAtt 'Memcached.ConfigurationEndpoint.Address'


resources:
  - ${file(resources.yml)}